### ISSUE TITLE
Play video Error

### ISSUE THREAD

**Issue by ToanMobile** [hitherejoe/LeanbackCards#2]
Binary XML file line #5: Error inflating class com.hitherejoe.leanbackcards.widget.PreviewCardView

Update I fix xml in library :com.hitherejoe.vineyard.ui.widget.LoopingVideoView -> com.hitherejoe.leanbackcards.widget.LoopingVideoView run ok.
Thanks you.

**Comment by hitherejoe** [comment]
@Huynhvantoan LeanbackCards is still in the last stages of development and hasn't been 'released' just yet. It'll be finished by next week so I'll give you a nudge and close this then. Thanks!

**Comment by hitherejoe** [comment]
@Huynhvantoan this has been implemented now, so i'll close this issue
