### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ryanseys** [hitherejoe/LeanbackCards#8]
Hi Joe, would be great to add a license to this project (and LICENSE file). Might I suggest Apache 2.0? :)

**Comment by ryanseys** [comment]
I just realized this is probably related to #5

**Comment by hitherejoe** [comment]
Ah yes, no problem - i'll do that at some point today!

**Comment by hitherejoe** [comment]
All done! :) (Sorry for the delay...)

**Comment by ryanseys** [comment]
Cheers!
